modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${mod_repo}/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${project.version}"
displayName="${mod_name}"
displayURL="${mod_repo}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="icon.png"

[[mixins]]
config="minihudextra-common.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="architectury"
type="required"
versionRange="[${architectury_dependency},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="bocchud"
type="required"
versionRange="[0.4.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId = "mafglib"
type = "required"
versionRange = "[0.4.2,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "ftbultimine"
type = "optional"
versionRange = ""
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "sereneseasons"
type = "optional"
versionRange = ""
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "glitchcore"
type = "optional"
versionRange = ""
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "naturesaura"
type = "optional"
versionRange = ""
ordering = "AFTER"
side = "CLIENT"